//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.DTO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralAppearance1EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralAppearance1EnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.DTO.Resources.GeneralAppearance1EnumResource", typeof(GeneralAppearance1EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyanosis.
        /// </summary>
        public static string Cyanosis {
            get {
                return ResourceManager.GetString("Cyanosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grave.
        /// </summary>
        public static string Grave {
            get {
                return ResourceManager.GetString("Grave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaundice.
        /// </summary>
        public static string Jaundice {
            get {
                return ResourceManager.GetString("Jaundice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallor.
        /// </summary>
        public static string Pallor {
            get {
                return ResourceManager.GetString("Pallor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string Poor {
            get {
                return ResourceManager.GetString("Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well.
        /// </summary>
        public static string Well {
            get {
                return ResourceManager.GetString("Well", resourceCulture);
            }
        }
    }
}
