//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.DTO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NICUResuscitationEnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NICUResuscitationEnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.DTO.Resources.NICUResuscitationEnumResource", typeof(NICUResuscitationEnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrenaline doses No..
        /// </summary>
        public static string AdrenalineDoses {
            get {
                return ResourceManager.GetString("AdrenalineDoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood transfusion.
        /// </summary>
        public static string BloodTransfusion {
            get {
                return ResourceManager.GetString("BloodTransfusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest compression.
        /// </summary>
        public static string ChestCompression {
            get {
                return ResourceManager.GetString("ChestCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold clamping delay (30 - 60 sec.
        /// </summary>
        public static string ColdClamping {
            get {
                return ResourceManager.GetString("ColdClamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cord blood gases.
        /// </summary>
        public static string CordBloodGases {
            get {
                return ResourceManager.GetString("CordBloodGases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPAP.
        /// </summary>
        public static string CPAP {
            get {
                return ResourceManager.GetString("CPAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drying.
        /// </summary>
        public static string Drying {
            get {
                return ResourceManager.GetString("Drying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming.
        /// </summary>
        public static string Heating {
            get {
                return ResourceManager.GetString("Heating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HFNC.
        /// </summary>
        public static string HFNC {
            get {
                return ResourceManager.GetString("HFNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intubation.
        /// </summary>
        public static string Intubation {
            get {
                return ResourceManager.GetString("Intubation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPV.
        /// </summary>
        public static string PPV {
            get {
                return ResourceManager.GetString("PPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretions Suctioning.
        /// </summary>
        public static string SecretionsSuctioning {
            get {
                return ResourceManager.GetString("SecretionsSuctioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin-to-skin care.
        /// </summary>
        public static string SkinToskin {
            get {
                return ResourceManager.GetString("SkinToskin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVC.
        /// </summary>
        public static string UVC {
            get {
                return ResourceManager.GetString("UVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume expanders.
        /// </summary>
        public static string VolumeExpanders {
            get {
                return ResourceManager.GetString("VolumeExpanders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap in a polyethylene plastic bag.
        /// </summary>
        public static string Wrappolyethylene {
            get {
                return ResourceManager.GetString("Wrappolyethylene", resourceCulture);
            }
        }
    }
}
