//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.DTO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RiskFactorsEnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RiskFactorsEnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.DTO.Resources.RiskFactorsEnumResource", typeof(RiskFactorsEnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        public static string Diabetes {
            get {
                return ResourceManager.GetString("Diabetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Story.
        /// </summary>
        public static string FamilyStory {
            get {
                return ResourceManager.GetString("FamilyStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fats.
        /// </summary>
        public static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity.
        /// </summary>
        public static string Obesity {
            get {
                return ResourceManager.GetString("Obesity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        public static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stress.
        /// </summary>
        public static string Stress {
            get {
                return ResourceManager.GetString("Stress", resourceCulture);
            }
        }
    }
}
