//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClinicalStoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClinicalStoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.ClinicalStoryResource", typeof(ClinicalStoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanying Person .
        /// </summary>
        public static string AccompanyingPersonExisted {
            get {
                return ResourceManager.GetString("AccompanyingPersonExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A- Appearance, behavior and cooperation with the examiner.
        /// </summary>
        public static string AppearanceBehaviorAndCooperationWithTheExaminer {
            get {
                return ResourceManager.GetString("AppearanceBehaviorAndCooperationWithTheExaminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter appearance, behavior, and cooperation with the examiner.
        /// </summary>
        public static string AppearanceBehaviorAndCooperationWithTheExaminerInfoSpan {
            get {
                return ResourceManager.GetString("AppearanceBehaviorAndCooperationWithTheExaminerInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Summary.
        /// </summary>
        public static string CaseSummary {
            get {
                return ResourceManager.GetString("CaseSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter case summary.
        /// </summary>
        public static string CaseSummaryInfoSpan {
            get {
                return ResourceManager.GetString("CaseSummaryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of referral.
        /// </summary>
        public static string CauseOfReferral {
            get {
                return ResourceManager.GetString("CauseOfReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter cause of referral.
        /// </summary>
        public static string CauseOfReferralInfoSpan {
            get {
                return ResourceManager.GetString("CauseOfReferralInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics of the pre-disorder.
        /// </summary>
        public static string CharacteristicsOfThePreDisorder {
            get {
                return ResourceManager.GetString("CharacteristicsOfThePreDisorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter characteristics of the pre-disorder.
        /// </summary>
        public static string CharacteristicsOfThePreDisorderInfoSpan {
            get {
                return ResourceManager.GetString("CharacteristicsOfThePreDisorderInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Story.
        /// </summary>
        public static string ClinicalStory {
            get {
                return ResourceManager.GetString("ClinicalStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the complaint.
        /// </summary>
        public static string ComplaintDetails {
            get {
                return ResourceManager.GetString("ComplaintDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter details of the complaint.
        /// </summary>
        public static string ComplaintDetailsInfoSpan {
            get {
                return ResourceManager.GetString("ComplaintDetailsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current complaint as expressed by the beneficiary “beneficiary’s talk”.
        /// </summary>
        public static string CurrentComplaint {
            get {
                return ResourceManager.GetString("CurrentComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter remarks current complaint.
        /// </summary>
        public static string CurrentComplaintInfoSpan {
            get {
                return ResourceManager.GetString("CurrentComplaintInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current place residence.
        /// </summary>
        public static string CurrentPlaceResidence {
            get {
                return ResourceManager.GetString("CurrentPlaceResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter current place residence.
        /// </summary>
        public static string CurrentPlaceResidenceInfoSpan {
            get {
                return ResourceManager.GetString("CurrentPlaceResidenceInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Work.
        /// </summary>
        public static string CurrentWork {
            get {
                return ResourceManager.GetString("CurrentWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the current work.
        /// </summary>
        public static string CurrentWorkInfoSpan {
            get {
                return ResourceManager.GetString("CurrentWorkInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial differential diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string DiagnosisTitle {
            get {
                return ResourceManager.GetString("DiagnosisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Level.
        /// </summary>
        public static string EducationalLevel {
            get {
                return ResourceManager.GetString("EducationalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter educational level.
        /// </summary>
        public static string EducationalLevelInfoSpan {
            get {
                return ResourceManager.GetString("EducationalLevelInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existed.
        /// </summary>
        public static string Existed {
            get {
                return ResourceManager.GetString("Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Precedents.
        /// </summary>
        public static string FamilyPrecedents {
            get {
                return ResourceManager.GetString("FamilyPrecedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter family frecedents.
        /// </summary>
        public static string FamilyPrecedentsInfoSpan {
            get {
                return ResourceManager.GetString("FamilyPrecedentsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General medical precedents &quot;organic diseases, surgeries&quot;.
        /// </summary>
        public static string GeneralMedicalPrecedents {
            get {
                return ResourceManager.GetString("GeneralMedicalPrecedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter general medical precedents &quot;organic diseases, surgeries&quot;.
        /// </summary>
        public static string GeneralMedicalPrecedentsInfoSpan {
            get {
                return ResourceManager.GetString("GeneralMedicalPrecedentsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D - Mood and Affection.
        /// </summary>
        public static string MoodAndAffection {
            get {
                return ResourceManager.GetString("MoodAndAffection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mood and affection.
        /// </summary>
        public static string MoodAndAffectionInfoSpan {
            get {
                return ResourceManager.GetString("MoodAndAffectionInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most likely diagnosis.
        /// </summary>
        public static string MostLikelyDiagnosis {
            get {
                return ResourceManager.GetString("MostLikelyDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the most likely diagnosis.
        /// </summary>
        public static string MostLikelyDiagnosisInfoSpan {
            get {
                return ResourceManager.GetString("MostLikelyDiagnosisInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Brothers.
        /// </summary>
        public static string NumberOfBrothers {
            get {
                return ResourceManager.GetString("NumberOfBrothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number of brothers.
        /// </summary>
        public static string NumberOfBrothersInfoSpan {
            get {
                return ResourceManager.GetString("NumberOfBrothersInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F- Perception and Consciousness.
        /// </summary>
        public static string PerceptionAndConsciousness {
            get {
                return ResourceManager.GetString("PerceptionAndConsciousness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter perception and consciousness.
        /// </summary>
        public static string PerceptionAndConsciousnessInfoSpan {
            get {
                return ResourceManager.GetString("PerceptionAndConsciousnessInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of interview.
        /// </summary>
        public static string PlaceOfInterview {
            get {
                return ResourceManager.GetString("PlaceOfInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter place of interview.
        /// </summary>
        public static string PlaceOfInterviewInfoSpan {
            get {
                return ResourceManager.GetString("PlaceOfInterviewInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Place Residence.
        /// </summary>
        public static string PreviousPlaceResidence {
            get {
                return ResourceManager.GetString("PreviousPlaceResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous place residence.
        /// </summary>
        public static string PreviousPlaceResidenceInfoSpan {
            get {
                return ResourceManager.GetString("PreviousPlaceResidenceInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Work.
        /// </summary>
        public static string PreviousWork {
            get {
                return ResourceManager.GetString("PreviousWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous work.
        /// </summary>
        public static string PreviousWorkInfoSpan {
            get {
                return ResourceManager.GetString("PreviousWorkInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychological Examination.
        /// </summary>
        public static string PsychologicalExamination {
            get {
                return ResourceManager.GetString("PsychologicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychological, neurological and personal addictive precedents.
        /// </summary>
        public static string PsychologicalNeurologicalAndPersonalAddictivePrecedents {
            get {
                return ResourceManager.GetString("PsychologicalNeurologicalAndPersonalAddictivePrecedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter psychological, neurological and personal addictive precedents.
        /// </summary>
        public static string PsychologicalNeurologicalAndPersonalAddictivePrecedentsInfoSpan {
            get {
                return ResourceManager.GetString("PsychologicalNeurologicalAndPersonalAddictivePrecedentsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B- Psychomotor Activity.
        /// </summary>
        public static string PsychomotorActivity {
            get {
                return ResourceManager.GetString("PsychomotorActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter psychomotor activity.
        /// </summary>
        public static string PsychomotorActivityInfoSpan {
            get {
                return ResourceManager.GetString("PsychomotorActivityInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter remarks.
        /// </summary>
        public static string RemarksInfoSpan {
            get {
                return ResourceManager.GetString("RemarksInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Assessment.
        /// </summary>
        public static string RiskAssessment {
            get {
                return ResourceManager.GetString("RiskAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter risk assessment.
        /// </summary>
        public static string RiskAssessmentInfoSpan {
            get {
                return ResourceManager.GetString("RiskAssessmentInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G- Sense and Cognition.
        /// </summary>
        public static string SenseAndCognition {
            get {
                return ResourceManager.GetString("SenseAndCognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/D- Abstraction.
        /// </summary>
        public static string SenseAndCognition_Abstraction {
            get {
                return ResourceManager.GetString("SenseAndCognition_Abstraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter abstraction.
        /// </summary>
        public static string SenseAndCognition_AbstractionInfoSpan {
            get {
                return ResourceManager.GetString("SenseAndCognition_AbstractionInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/C- Attention and Concentration.
        /// </summary>
        public static string SenseAndCognition_AttentionAndConcentration {
            get {
                return ResourceManager.GetString("SenseAndCognition_AttentionAndConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter attention and concentration.
        /// </summary>
        public static string SenseAndCognition_AttentionAndConcentrationInfoSpan {
            get {
                return ResourceManager.GetString("SenseAndCognition_AttentionAndConcentrationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/A- Consciousness and Orientation.
        /// </summary>
        public static string SenseAndCognition_ConsciousnessAndOrientation {
            get {
                return ResourceManager.GetString("SenseAndCognition_ConsciousnessAndOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter consciousness and orientation.
        /// </summary>
        public static string SenseAndCognition_ConsciousnessAndOrientationInfoSpan {
            get {
                return ResourceManager.GetString("SenseAndCognition_ConsciousnessAndOrientationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/F- Insight.
        /// </summary>
        public static string SenseAndCognition_Insight {
            get {
                return ResourceManager.GetString("SenseAndCognition_Insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter insight.
        /// </summary>
        public static string SenseAndCognition_InsightInfoSpan {
            get {
                return ResourceManager.GetString("SenseAndCognition_InsightInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/E- Judgment.
        /// </summary>
        public static string SenseAndCognition_Judgment {
            get {
                return ResourceManager.GetString("SenseAndCognition_Judgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter judgment.
        /// </summary>
        public static string SenseAndCognition_JudgmentInfoSpan {
            get {
                return ResourceManager.GetString("SenseAndCognition_JudgmentInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/B - Memory.
        /// </summary>
        public static string SenseAndCognition_Memory {
            get {
                return ResourceManager.GetString("SenseAndCognition_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter memory.
        /// </summary>
        public static string SenseAndCognition_MemoryInfoSpan {
            get {
                return ResourceManager.GetString("SenseAndCognition_MemoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Story (marriage, work, adolescence and childhood, etc.).
        /// </summary>
        public static string SocialStory {
            get {
                return ResourceManager.GetString("SocialStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter social story.
        /// </summary>
        public static string SocialStoryInfoSpan {
            get {
                return ResourceManager.GetString("SocialStoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of Referral.
        /// </summary>
        public static string SourceOfReferral {
            get {
                return ResourceManager.GetString("SourceOfReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter source of referral.
        /// </summary>
        public static string SourceOfReferralInfoSpan {
            get {
                return ResourceManager.GetString("SourceOfReferralInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C- Speech.
        /// </summary>
        public static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter speech.
        /// </summary>
        public static string SpeechInfoSpan {
            get {
                return ResourceManager.GetString("SpeechInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Diagnosis.
        /// </summary>
        public static string SubDiagnosisTitle {
            get {
                return ResourceManager.GetString("SubDiagnosisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Thinking.
        /// </summary>
        public static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter E- Thinking.
        /// </summary>
        public static string ThinkingInfoSpan {
            get {
                return ResourceManager.GetString("ThinkingInfoSpan", resourceCulture);
            }
        }
    }
}
