//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ICU Case.
        /// </summary>
        public static string AddICUCase {
            get {
                return ResourceManager.GetString("AddICUCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding.
        /// </summary>
        public static string Adding {
            get {
                return ResourceManager.GetString("Adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNewTooltip {
            get {
                return ResourceManager.GetString("AddNewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not choose same Diagnosis more than one time!!.
        /// </summary>
        public static string CannotChooseSameDiagnosis {
            get {
                return ResourceManager.GetString("CannotChooseSameDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Closure.
        /// </summary>
        public static string CaseClosure {
            get {
                return ResourceManager.GetString("CaseClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Closure Reason.
        /// </summary>
        public static string CaseClosureReason {
            get {
                return ResourceManager.GetString("CaseClosureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select case closure reason.
        /// </summary>
        public static string CaseClosureReasonInfoSpan {
            get {
                return ResourceManager.GetString("CaseClosureReasonInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases Closure.
        /// </summary>
        public static string CaseClosures {
            get {
                return ResourceManager.GetString("CaseClosures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Sub Diagnoses!!.
        /// </summary>
        public static string ChooseSubDiagnoses {
            get {
                return ResourceManager.GetString("ChooseSubDiagnoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Case.
        /// </summary>
        public static string CloseCase {
            get {
                return ResourceManager.GetString("CloseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Closed.
        /// </summary>
        public static string CloseCaseMessage {
            get {
                return ResourceManager.GetString("CloseCaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure Note.
        /// </summary>
        public static string ClosureNote {
            get {
                return ResourceManager.GetString("ClosureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter closure notes.
        /// </summary>
        public static string ClosureNoteInfoSpan {
            get {
                return ResourceManager.GetString("ClosureNoteInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string DeleteConfirmContent {
            get {
                return ResourceManager.GetString("DeleteConfirmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        public static string DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All.
        /// </summary>
        public static string DownloadALL {
            get {
                return ResourceManager.GetString("DownloadALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        public static string ExportExcelTooltip {
            get {
                return ResourceManager.GetString("ExportExcelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Pdf.
        /// </summary>
        public static string ExportPdfTooltip {
            get {
                return ResourceManager.GetString("ExportPdfTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To PDF.
        /// </summary>
        public static string ExportToPDF {
            get {
                return ResourceManager.GetString("ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string Handle {
            get {
                return ResourceManager.GetString("Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICU.
        /// </summary>
        public static string ICU {
            get {
                return ResourceManager.GetString("ICU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICU Cases.
        /// </summary>
        public static string ICUCases {
            get {
                return ResourceManager.GetString("ICUCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involved Consultants.
        /// </summary>
        public static string InvolvedConsultants {
            get {
                return ResourceManager.GetString("InvolvedConsultants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involved Service Providers.
        /// </summary>
        public static string InvolvedServiceProviders {
            get {
                return ResourceManager.GetString("InvolvedServiceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Topic.
        /// </summary>
        public static string MeetTopic {
            get {
                return ResourceManager.GetString("MeetTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Health.
        /// </summary>
        public static string MentalHealth {
            get {
                return ResourceManager.GetString("MentalHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Health Cases.
        /// </summary>
        public static string MentalHealthCases {
            get {
                return ResourceManager.GetString("MentalHealthCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Avg.
        /// </summary>
        public static string MonthlyAvg {
            get {
                return ResourceManager.GetString("MonthlyAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notifications.
        /// </summary>
        public static string MyNotifications {
            get {
                return ResourceManager.GetString("MyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Patients.
        /// </summary>
        public static string MyPatients {
            get {
                return ResourceManager.GetString("MyPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPICU.
        /// </summary>
        public static string NPICU {
            get {
                return ResourceManager.GetString("NPICU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPICU Cases.
        /// </summary>
        public static string NPICUCases {
            get {
                return ResourceManager.GetString("NPICUCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Oprions {
            get {
                return ResourceManager.GetString("Oprions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Information.
        /// </summary>
        public static string PatientInfo {
            get {
                return ResourceManager.GetString("PatientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile info.
        /// </summary>
        public static string Profileinfo {
            get {
                return ResourceManager.GetString("Profileinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshTooltip {
            get {
                return ResourceManager.GetString("RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReOpen Case.
        /// </summary>
        public static string ReOpenCase {
            get {
                return ResourceManager.GetString("ReOpenCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Reopened.
        /// </summary>
        public static string ReOpenCaseMessage {
            get {
                return ResourceManager.GetString("ReOpenCaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string RequiredFeild {
            get {
                return ResourceManager.GetString("RequiredFeild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File....
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Closures.
        /// </summary>
        public static string ShowClosures {
            get {
                return ResourceManager.GetString("ShowClosures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields are required.
        /// </summary>
        public static string SomeFeildIsRequired {
            get {
                return ResourceManager.GetString("SomeFeildIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding, has been completed successfully.
        /// </summary>
        public static string SuccessfullyAddedMSG {
            get {
                return ResourceManager.GetString("SuccessfullyAddedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting, has been completed successfully.
        /// </summary>
        public static string SuccessfullyDeletedMSG {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing, has been completed successfully.
        /// </summary>
        public static string SuccessfullyUpdatedMSG {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string ThisFieldisRequired {
            get {
                return ResourceManager.GetString("ThisFieldisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Patients In ICU.
        /// </summary>
        public static string TotalPatientsInICU {
            get {
                return ResourceManager.GetString("TotalPatientsInICU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Patients In Mental Health.
        /// </summary>
        public static string TotalPatientsInMentalHealth {
            get {
                return ResourceManager.GetString("TotalPatientsInMentalHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Patients In NPICU.
        /// </summary>
        public static string TotalPatientsInNPICU {
            get {
                return ResourceManager.GetString("TotalPatientsInNPICU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
