//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ICUClinicalStoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICUClinicalStoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.ICUClinicalStoryResource", typeof(ICUClinicalStoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Date.
        /// </summary>
        public static string AcceptanceDate {
            get {
                return ResourceManager.GetString("AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter acceptance date.
        /// </summary>
        public static string AcceptanceDateInfoSpan {
            get {
                return ResourceManager.GetString("AcceptanceDateInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aortic Valve.
        /// </summary>
        public static string AorticValve {
            get {
                return ResourceManager.GetString("AorticValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter aortic valve.
        /// </summary>
        public static string AorticValveInfoSpan {
            get {
                return ResourceManager.GetString("AorticValveInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP.
        /// </summary>
        public static string BP {
            get {
                return ResourceManager.GetString("BP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter BP.
        /// </summary>
        public static string BPInfoSpan {
            get {
                return ResourceManager.GetString("BPInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Story.
        /// </summary>
        public static string ClinicalStory {
            get {
                return ResourceManager.GetString("ClinicalStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Details.
        /// </summary>
        public static string ComplaintDetails {
            get {
                return ResourceManager.GetString("ComplaintDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter complaint details.
        /// </summary>
        public static string ComplaintDetailsInfoSpan {
            get {
                return ResourceManager.GetString("ComplaintDetailsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter complaint.
        /// </summary>
        public static string ComplaintInfoSpan {
            get {
                return ResourceManager.GetString("ComplaintInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cvs.
        /// </summary>
        public static string Cvs {
            get {
                return ResourceManager.GetString("Cvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Cvs.
        /// </summary>
        public static string CvsInfoSpan {
            get {
                return ResourceManager.GetString("CvsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cxr.
        /// </summary>
        public static string Cxr {
            get {
                return ResourceManager.GetString("Cxr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Cxr.
        /// </summary>
        public static string CxrInfoSpan {
            get {
                return ResourceManager.GetString("CxrInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter diagnosis.
        /// </summary>
        public static string DiagnosisInfoSpan {
            get {
                return ResourceManager.GetString("DiagnosisInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Status.
        /// </summary>
        public static string DiagnosisStatus {
            get {
                return ResourceManager.GetString("DiagnosisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs details (if yes).
        /// </summary>
        public static string DrugsDetails {
            get {
                return ResourceManager.GetString("DrugsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter drugs details.
        /// </summary>
        public static string DrugsDetailsInfoSpan {
            get {
                return ResourceManager.GetString("DrugsDetailsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECG.
        /// </summary>
        public static string ECG {
            get {
                return ResourceManager.GetString("ECG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter ECG.
        /// </summary>
        public static string ECGInfoSpan {
            get {
                return ResourceManager.GetString("ECGInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF.
        /// </summary>
        public static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter EF.
        /// </summary>
        public static string EFInfoSpan {
            get {
                return ResourceManager.GetString("EFInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there an allergy to drugs?.
        /// </summary>
        public static string IsThereAnAllergyToDrugs {
            get {
                return ResourceManager.GetString("IsThereAnAllergyToDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string IsThereAnAllergyToDrugsInfoSpan {
            get {
                return ResourceManager.GetString("IsThereAnAllergyToDrugsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History.
        /// </summary>
        public static string MedicalHistory {
            get {
                return ResourceManager.GetString("MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter medical history.
        /// </summary>
        public static string MedicalHistoryInfoSpan {
            get {
                return ResourceManager.GetString("MedicalHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitral Valve.
        /// </summary>
        public static string MitralValve {
            get {
                return ResourceManager.GetString("MitralValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mitral valve.
        /// </summary>
        public static string MitralValveInfoSpan {
            get {
                return ResourceManager.GetString("MitralValveInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter others.
        /// </summary>
        public static string OthersInfoSpan {
            get {
                return ResourceManager.GetString("OthersInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacological Precedents.
        /// </summary>
        public static string PharmacologicalPrecedents {
            get {
                return ResourceManager.GetString("PharmacologicalPrecedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pharmacological precedents.
        /// </summary>
        public static string PharmacologicalPrecedentsInfoSpan {
            get {
                return ResourceManager.GetString("PharmacologicalPrecedentsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Catheter.
        /// </summary>
        public static string PreviousCatheter {
            get {
                return ResourceManager.GetString("PreviousCatheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous catheter.
        /// </summary>
        public static string PreviousCatheterInfoSpan {
            get {
                return ResourceManager.GetString("PreviousCatheterInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Surgical History.
        /// </summary>
        public static string PreviousSurgicalHistory {
            get {
                return ResourceManager.GetString("PreviousSurgicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous surgical history.
        /// </summary>
        public static string PreviousSurgicalHistoryInfoSpan {
            get {
                return ResourceManager.GetString("PreviousSurgicalHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pulse.
        /// </summary>
        public static string PulseInfoSpan {
            get {
                return ResourceManager.GetString("PulseInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Factors.
        /// </summary>
        public static string RiskFactors {
            get {
                return ResourceManager.GetString("RiskFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select risk factors.
        /// </summary>
        public static string RiskFactorsInfoSpan {
            get {
                return ResourceManager.GetString("RiskFactorsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultrasound Heart Scan.
        /// </summary>
        public static string UltrasoundHeartScan {
            get {
                return ResourceManager.GetString("UltrasoundHeartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter ultrasound heart scan.
        /// </summary>
        public static string UltrasoundHeartScanInfoSpan {
            get {
                return ResourceManager.GetString("UltrasoundHeartScanInfoSpan", resourceCulture);
            }
        }
    }
}
