//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ICUExitResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICUExitResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.ICUExitResource", typeof(ICUExitResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        public static string BloodPressure {
            get {
                return ResourceManager.GetString("BloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter blood pressure.
        /// </summary>
        public static string BloodPressureInfoSpan {
            get {
                return ResourceManager.GetString("BloodPressureInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter diagnosis.
        /// </summary>
        public static string DiagnosisInfoSpan {
            get {
                return ResourceManager.GetString("DiagnosisInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Exit Status Report.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter medication.
        /// </summary>
        public static string MedicationInfoSpan {
            get {
                return ResourceManager.GetString("MedicationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygenation.
        /// </summary>
        public static string Oxygenation {
            get {
                return ResourceManager.GetString("Oxygenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter oxygenation.
        /// </summary>
        public static string OxygenationInfoSpan {
            get {
                return ResourceManager.GetString("OxygenationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pulse.
        /// </summary>
        public static string PulseInfoSpan {
            get {
                return ResourceManager.GetString("PulseInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter recommendations.
        /// </summary>
        public static string RecommendationsInfoSpan {
            get {
                return ResourceManager.GetString("RecommendationsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter temperature.
        /// </summary>
        public static string TemperatureInfoSpan {
            get {
                return ResourceManager.GetString("TemperatureInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment / Recovery.
        /// </summary>
        public static string TemperatureRecovery {
            get {
                return ResourceManager.GetString("TemperatureRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter treatment / recovery.
        /// </summary>
        public static string TemperatureRecoveryInfoSpan {
            get {
                return ResourceManager.GetString("TemperatureRecoveryInfoSpan", resourceCulture);
            }
        }
    }
}
