//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ICUInternalConsultationFormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICUInternalConsultationFormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.ICUInternalConsultationFormResource", typeof(ICUInternalConsultationFormResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Surgery.
        /// </summary>
        public static string DateOfSurgery {
            get {
                return ResourceManager.GetString("DateOfSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date of surgery.
        /// </summary>
        public static string DateOfSurgeryInfoSpan {
            get {
                return ResourceManager.GetString("DateOfSurgeryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter diagnosis.
        /// </summary>
        public static string DiagnosisInfoSpan {
            get {
                return ResourceManager.GetString("DiagnosisInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Consultation Form.
        /// </summary>
        public static string InternalConsultationForm {
            get {
                return ResourceManager.GetString("InternalConsultationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Doctor.
        /// </summary>
        public static string NameOfDoctor {
            get {
                return ResourceManager.GetString("NameOfDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name of doctor.
        /// </summary>
        public static string NameOfDoctorInfoSpan {
            get {
                return ResourceManager.GetString("NameOfDoctorInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter recommendations.
        /// </summary>
        public static string RecommendationsInfoSpan {
            get {
                return ResourceManager.GetString("RecommendationsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Anesthesia.
        /// </summary>
        public static string UndeAnesthesia {
            get {
                return ResourceManager.GetString("UndeAnesthesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter under anesthesia.
        /// </summary>
        public static string UndeAnesthesiaInfoSpan {
            get {
                return ResourceManager.GetString("UndeAnesthesiaInfoSpan", resourceCulture);
            }
        }
    }
}
