//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ICULabUnitResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICULabUnitResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.ICULabUnitResource", typeof(ICULabUnitResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lab Unit.
        /// </summary>
        public static string AddLabUnit {
            get {
                return ResourceManager.GetString("AddLabUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        public static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Gases.
        /// </summary>
        public static string BloodGases {
            get {
                return ResourceManager.GetString("BloodGases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium (mg/dL).
        /// </summary>
        public static string Calcium {
            get {
                return ResourceManager.GetString("Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBC.
        /// </summary>
        public static string CBC {
            get {
                return ResourceManager.GetString("CBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string CBCBloodGroup {
            get {
                return ResourceManager.GetString("CBCBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.B.
        /// </summary>
        public static string CBCHB {
            get {
                return ResourceManager.GetString("CBCHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.T.
        /// </summary>
        public static string CBCHT {
            get {
                return ResourceManager.GetString("CBCHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string CBCL {
            get {
                return ResourceManager.GetString("CBCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string CBCM {
            get {
                return ResourceManager.GetString("CBCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string CBCN {
            get {
                return ResourceManager.GetString("CBCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLT.
        /// </summary>
        public static string CBCPLT {
            get {
                return ResourceManager.GetString("CBCPLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.B.C.
        /// </summary>
        public static string CBCWBC {
            get {
                return ResourceManager.GetString("CBCWBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry.
        /// </summary>
        public static string Chemistry {
            get {
                return ResourceManager.GetString("Chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albumin.
        /// </summary>
        public static string ChemistryAlbumin {
            get {
                return ResourceManager.GetString("ChemistryAlbumin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALP.
        /// </summary>
        public static string ChemistryALP {
            get {
                return ResourceManager.GetString("ChemistryALP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amylase.
        /// </summary>
        public static string ChemistryAmylase {
            get {
                return ResourceManager.GetString("ChemistryAmylase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilir.Dirct.
        /// </summary>
        public static string ChemistryBilirDirct {
            get {
                return ResourceManager.GetString("ChemistryBilirDirct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blllr.Indirect.
        /// </summary>
        public static string ChemistryBilirIndirect {
            get {
                return ResourceManager.GetString("ChemistryBilirIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilir.Total.
        /// </summary>
        public static string ChemistryBilirTotal {
            get {
                return ResourceManager.GetString("ChemistryBilirTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CKMP.
        /// </summary>
        public static string ChemistryCKMB {
            get {
                return ResourceManager.GetString("ChemistryCKMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine.
        /// </summary>
        public static string ChemistryCreatinine {
            get {
                return ResourceManager.GetString("ChemistryCreatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRP.
        /// </summary>
        public static string ChemistryCRP {
            get {
                return ResourceManager.GetString("ChemistryCRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globulins.
        /// </summary>
        public static string ChemistryGlobulins {
            get {
                return ResourceManager.GetString("ChemistryGlobulins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        public static string ChemistryGlucose {
            get {
                return ResourceManager.GetString("ChemistryGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.G.P.T.
        /// </summary>
        public static string ChemistrySGPT {
            get {
                return ResourceManager.GetString("ChemistrySGPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Proteins.
        /// </summary>
        public static string ChemistryTotalProteins {
            get {
                return ResourceManager.GetString("ChemistryTotalProteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urea.
        /// </summary>
        public static string ChemistryUrea {
            get {
                return ResourceManager.GetString("ChemistryUrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chloride.
        /// </summary>
        public static string Chloride {
            get {
                return ResourceManager.GetString("Chloride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string CoagulationActivity {
            get {
                return ResourceManager.GetString("CoagulationActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleeding Time.
        /// </summary>
        public static string CoagulationBleedingTime {
            get {
                return ResourceManager.GetString("CoagulationBleedingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clotting Time.
        /// </summary>
        public static string CoagulationClottingtime {
            get {
                return ResourceManager.GetString("CoagulationClottingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string CoagulationControl {
            get {
                return ResourceManager.GetString("CoagulationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INR.
        /// </summary>
        public static string CoagulationINR {
            get {
                return ResourceManager.GetString("CoagulationINR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (O).
        /// </summary>
        public static string CoagulationO {
            get {
                return ResourceManager.GetString("CoagulationO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string CoagulationPatient {
            get {
                return ResourceManager.GetString("CoagulationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        public static string CoagulationPT {
            get {
                return ResourceManager.GetString("CoagulationPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coagulation Test.
        /// </summary>
        public static string CoagulationTest {
            get {
                return ResourceManager.GetString("CoagulationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrolytes.
        /// </summary>
        public static string Electrolytes {
            get {
                return ResourceManager.GetString("Electrolytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Attachment.
        /// </summary>
        public static string GeneralAttachment {
            get {
                return ResourceManager.GetString("GeneralAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCO3.
        /// </summary>
        public static string HCO3 {
            get {
                return ResourceManager.GetString("HCO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Unit.
        /// </summary>
        public static string LabUnit {
            get {
                return ResourceManager.GetString("LabUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Units.
        /// </summary>
        public static string LabUnits {
            get {
                return ResourceManager.GetString("LabUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium.
        /// </summary>
        public static string Magnesium {
            get {
                return ResourceManager.GetString("Magnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCO2.
        /// </summary>
        public static string PCO2 {
            get {
                return ResourceManager.GetString("PCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        public static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorous.
        /// </summary>
        public static string Phosphorous {
            get {
                return ResourceManager.GetString("Phosphorous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO2.
        /// </summary>
        public static string PO2 {
            get {
                return ResourceManager.GetString("PO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        public static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serology.
        /// </summary>
        public static string SEROLOGY {
            get {
                return ResourceManager.GetString("SEROLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (A).
        /// </summary>
        public static string SerologyA {
            get {
                return ResourceManager.GetString("SerologyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (M).
        /// </summary>
        public static string SerologyCoagulationM {
            get {
                return ResourceManager.GetString("SerologyCoagulationM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (H).
        /// </summary>
        public static string SerologyH {
            get {
                return ResourceManager.GetString("SerologyH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hbs Ag.
        /// </summary>
        public static string SerologyHBSAG {
            get {
                return ResourceManager.GetString("SerologyHBSAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.C.V.
        /// </summary>
        public static string SerologyHCV {
            get {
                return ResourceManager.GetString("SerologyHCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.I.V.
        /// </summary>
        public static string SerologyHIV {
            get {
                return ResourceManager.GetString("SerologyHIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (M).
        /// </summary>
        public static string SerologyM {
            get {
                return ResourceManager.GetString("SerologyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (O).
        /// </summary>
        public static string SerologyO {
            get {
                return ResourceManager.GetString("SerologyO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TROPONIN T.
        /// </summary>
        public static string TROPONINT {
            get {
                return ResourceManager.GetString("TROPONINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amorphous Urate.
        /// </summary>
        public static string UrineAmorphousUrate {
            get {
                return ResourceManager.GetString("UrineAmorphousUrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string UrineAppearance {
            get {
                return ResourceManager.GetString("UrineAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacteria.
        /// </summary>
        public static string UrineBacteria {
            get {
                return ResourceManager.GetString("UrineBacteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billlrubin.
        /// </summary>
        public static string UrineBilllrubin {
            get {
                return ResourceManager.GetString("UrineBilllrubin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium Oxalate.
        /// </summary>
        public static string UrineCalciumOxalate {
            get {
                return ResourceManager.GetString("UrineCalciumOxalate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candida.
        /// </summary>
        public static string UrineCandida {
            get {
                return ResourceManager.GetString("UrineCandida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string UrineColor {
            get {
                return ResourceManager.GetString("UrineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.Cells.
        /// </summary>
        public static string UrineECells {
            get {
                return ResourceManager.GetString("UrineECells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G Cylinders.
        /// </summary>
        public static string UrineGCylinders {
            get {
                return ResourceManager.GetString("UrineGCylinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        public static string UrineGlucose {
            get {
                return ResourceManager.GetString("UrineGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitones.
        /// </summary>
        public static string UrineKitones {
            get {
                return ResourceManager.GetString("UrineKitones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mucus.
        /// </summary>
        public static string UrineMucus {
            get {
                return ResourceManager.GetString("UrineMucus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        public static string UrinePH {
            get {
                return ResourceManager.GetString("UrinePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        public static string UrineProtein {
            get {
                return ResourceManager.GetString("UrineProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.B.C.
        /// </summary>
        public static string UrineRBC {
            get {
                return ResourceManager.GetString("UrineRBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.G.
        /// </summary>
        public static string UrineSG {
            get {
                return ResourceManager.GetString("UrineSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Test.
        /// </summary>
        public static string URINETEST {
            get {
                return ResourceManager.GetString("URINETEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U A Crystals.
        /// </summary>
        public static string UrineUACrystals {
            get {
                return ResourceManager.GetString("UrineUACrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.B.C.
        /// </summary>
        public static string UrineWBC {
            get {
                return ResourceManager.GetString("UrineWBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemoglobin.
        /// </summary>
        public static string UrintHemoglobin {
            get {
                return ResourceManager.GetString("UrintHemoglobin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widal.
        /// </summary>
        public static string Widal {
            get {
                return ResourceManager.GetString("Widal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wright.
        /// </summary>
        public static string Wright {
            get {
                return ResourceManager.GetString("Wright", resourceCulture);
            }
        }
    }
}
