//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ICUVitalSignResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICUVitalSignResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.ICUVitalSignResource", typeof(ICUVitalSignResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vital Sign.
        /// </summary>
        public static string AddVitalSign {
            get {
                return ResourceManager.GetString("AddVitalSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Glucose Levels.
        /// </summary>
        public static string BloodGlucoseLevels {
            get {
                return ResourceManager.GetString("BloodGlucoseLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drain 1.
        /// </summary>
        public static string Drain {
            get {
                return ResourceManager.GetString("Drain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emptying of Urine.
        /// </summary>
        public static string EmptyingOfUrine {
            get {
                return ResourceManager.GetString("EmptyingOfUrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat.
        /// </summary>
        public static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygenation.
        /// </summary>
        public static string Oxygenation {
            get {
                return ResourceManager.GetString("Oxygenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Mm Hg.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse (pulse/min).
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drain 2.
        /// </summary>
        public static string SecondDrain {
            get {
                return ResourceManager.GetString("SecondDrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string VitalSignDate {
            get {
                return ResourceManager.GetString("VitalSignDate", resourceCulture);
            }
        }
    }
}
