//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MedicationSchedulerFormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MedicationSchedulerFormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.MedicationSchedulerFormResource", typeof(MedicationSchedulerFormResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon 12.
        /// </summary>
        public static string Afternoon_12 {
            get {
                return ResourceManager.GetString("Afternoon_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon 2.
        /// </summary>
        public static string Afternoon_2 {
            get {
                return ResourceManager.GetString("Afternoon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon 4.
        /// </summary>
        public static string Afternoon_4 {
            get {
                return ResourceManager.GetString("Afternoon_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Concentration.
        /// </summary>
        public static string ConcentrationInfoSpan {
            get {
                return ResourceManager.GetString("ConcentrationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Name.
        /// </summary>
        public static string MedicationName {
            get {
                return ResourceManager.GetString("MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Medication Name.
        /// </summary>
        public static string MedicationNameInfoSpan {
            get {
                return ResourceManager.GetString("MedicationNameInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning 10.
        /// </summary>
        public static string Morning_10 {
            get {
                return ResourceManager.GetString("Morning_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning 12.
        /// </summary>
        public static string Morning_12 {
            get {
                return ResourceManager.GetString("Morning_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning 2.
        /// </summary>
        public static string Morning_2 {
            get {
                return ResourceManager.GetString("Morning_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning 4.
        /// </summary>
        public static string Morning_4 {
            get {
                return ResourceManager.GetString("Morning_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning 6.
        /// </summary>
        public static string Morning_6 {
            get {
                return ResourceManager.GetString("Morning_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning 8.
        /// </summary>
        public static string Morning_8 {
            get {
                return ResourceManager.GetString("Morning_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night 10.
        /// </summary>
        public static string Night_10 {
            get {
                return ResourceManager.GetString("Night_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night 6.
        /// </summary>
        public static string Night_6 {
            get {
                return ResourceManager.GetString("Night_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night 8.
        /// </summary>
        public static string Night_8 {
            get {
                return ResourceManager.GetString("Night_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Times.
        /// </summary>
        public static string NumberOfTimes {
            get {
                return ResourceManager.GetString("NumberOfTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Number Of Times.
        /// </summary>
        public static string NumberOfTimesInfoSpan {
            get {
                return ResourceManager.GetString("NumberOfTimesInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Of Administratin Of Drug.
        /// </summary>
        public static string RouteOfAdministratinOfDrug {
            get {
                return ResourceManager.GetString("RouteOfAdministratinOfDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Route Of Administratin Of Drug.
        /// </summary>
        public static string RouteOfAdministratinOfDrugInfoSpan {
            get {
                return ResourceManager.GetString("RouteOfAdministratinOfDrugInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
    }
}
