//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NICUConsultationFormFollowUPResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NICUConsultationFormFollowUPResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.NICUConsultationFormFollowUPResource" +
                            "", typeof(NICUConsultationFormFollowUPResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abortion.
        /// </summary>
        public static string Abortion {
            get {
                return ResourceManager.GetString("Abortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter abortion.
        /// </summary>
        public static string AbortionInfoSpan {
            get {
                return ResourceManager.GetString("AbortionInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add follow-up.
        /// </summary>
        public static string AddFollowUp {
            get {
                return ResourceManager.GetString("AddFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age at admission.
        /// </summary>
        public static string AgeAtAdmission {
            get {
                return ResourceManager.GetString("AgeAtAdmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter age at admission.
        /// </summary>
        public static string AgeAtAdmissionInfoSpan {
            get {
                return ResourceManager.GetString("AgeAtAdmissionInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apgar Score.
        /// </summary>
        public static string ApgarScore {
            get {
                return ResourceManager.GetString("ApgarScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5  th min.
        /// </summary>
        public static string ApgarScoreFifthMin {
            get {
                return ResourceManager.GetString("ApgarScoreFifthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 5 th min.
        /// </summary>
        public static string ApgarScoreFifthMinInfoSpan {
            get {
                return ResourceManager.GetString("ApgarScoreFifthMinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 th min.
        /// </summary>
        public static string ApgarScoreFirstMin {
            get {
                return ResourceManager.GetString("ApgarScoreFirstMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 1 th min.
        /// </summary>
        public static string ApgarScoreFirstMinInfoSpan {
            get {
                return ResourceManager.GetString("ApgarScoreFirstMinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 th min.
        /// </summary>
        public static string ApgarScoreTenthMin {
            get {
                return ResourceManager.GetString("ApgarScoreTenthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 10 th min.
        /// </summary>
        public static string ApgarScoreTenthMinInfoSpan {
            get {
                return ResourceManager.GetString("ApgarScoreTenthMinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth weight (gram).
        /// </summary>
        public static string BirthWeight {
            get {
                return ResourceManager.GetString("BirthWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter birth weight.
        /// </summary>
        public static string BirthWeightInfoSpan {
            get {
                return ResourceManager.GetString("BirthWeightInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP.
        /// </summary>
        public static string BP {
            get {
                return ResourceManager.GetString("BP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter BP.
        /// </summary>
        public static string BPInfoSpan {
            get {
                return ResourceManager.GetString("BPInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiovascular System.
        /// </summary>
        public static string CardiovascularSystem {
            get {
                return ResourceManager.GetString("CardiovascularSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter cardiovascular system.
        /// </summary>
        public static string CardiovascularSystemInfoSpan {
            get {
                return ResourceManager.GetString("CardiovascularSystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Nervous System.
        /// </summary>
        public static string CentralNervousSystem {
            get {
                return ResourceManager.GetString("CentralNervousSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter central nervous system.
        /// </summary>
        public static string CentralNervousSystemInfoSpan {
            get {
                return ResourceManager.GetString("CentralNervousSystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current pregnancy related medical history (Diabetes, hypertension, Oligoamnios, infection, etc…).
        /// </summary>
        public static string ChronicDiseasesAndPreviousObstetricalHistory {
            get {
                return ResourceManager.GetString("ChronicDiseasesAndPreviousObstetricalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter current pregnancy related medical history.
        /// </summary>
        public static string ChronicDiseasesAndPreviousObstetricalHistoryInfoSpan {
            get {
                return ResourceManager.GetString("ChronicDiseasesAndPreviousObstetricalHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronological age (after birth).
        /// </summary>
        public static string ChronologicalAge {
            get {
                return ResourceManager.GetString("ChronologicalAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter chronological age.
        /// </summary>
        public static string ChronologicalAgeInfoSpan {
            get {
                return ResourceManager.GetString("ChronologicalAgeInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter color.
        /// </summary>
        public static string ColorInfoSpan {
            get {
                return ResourceManager.GetString("ColorInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with family (Reason for admission, medical or surgical management, education, family support, etc…).
        /// </summary>
        public static string CommunicationWithFamily {
            get {
                return ResourceManager.GetString("CommunicationWithFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter communication with family.
        /// </summary>
        public static string CommunicationWithFamilyInfoSpan {
            get {
                return ResourceManager.GetString("CommunicationWithFamilyInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current illness history.
        /// </summary>
        public static string CurrentIllnessHistory {
            get {
                return ResourceManager.GetString("CurrentIllnessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter current illness history.
        /// </summary>
        public static string CurrentIllnessHistoryInfoSpan {
            get {
                return ResourceManager.GetString("CurrentIllnessHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current pregnancy related medical history (Diabetes, hypertension, Oligoamnios, infection, etc…).
        /// </summary>
        public static string CurrentPregnancyRelatedMedicalHistory {
            get {
                return ResourceManager.GetString("CurrentPregnancyRelatedMedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter current pregnancy related medical history.
        /// </summary>
        public static string CurrentPregnancyRelatedMedicalHistoryInfoSpan {
            get {
                return ResourceManager.GetString("CurrentPregnancyRelatedMedicalHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current weight (gram).
        /// </summary>
        public static string CurrentWeight {
            get {
                return ResourceManager.GetString("CurrentWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter current weight.
        /// </summary>
        public static string CurrentWeightInfoSpan {
            get {
                return ResourceManager.GetString("CurrentWeightInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family history (Consanguinity, congenital anomalies, metabolic disorders, etc…).
        /// </summary>
        public static string FamilyHistory {
            get {
                return ResourceManager.GetString("FamilyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter family history.
        /// </summary>
        public static string FamilyHistoryInfoSpan {
            get {
                return ResourceManager.GetString("FamilyHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter from.
        /// </summary>
        public static string FromInfoSpan {
            get {
                return ResourceManager.GetString("FromInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrointestinal Tract.
        /// </summary>
        public static string GastrointestinalTract {
            get {
                return ResourceManager.GetString("GastrointestinalTract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrointestinal Tract &amp; Genitourinary System.
        /// </summary>
        public static string GastrointestinalTractAndGenitourinarySystem {
            get {
                return ResourceManager.GetString("GastrointestinalTractAndGenitourinarySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gastrointestinal tract &amp; genitourinary system.
        /// </summary>
        public static string GastrointestinalTractAndGenitourinarySystemInfoSpan {
            get {
                return ResourceManager.GetString("GastrointestinalTractAndGenitourinarySystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gastrointestinal tract.
        /// </summary>
        public static string GastrointestinalTractInfoSpan {
            get {
                return ResourceManager.GetString("GastrointestinalTractInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genitourinary system.
        /// </summary>
        public static string GenitourinarySystem {
            get {
                return ResourceManager.GetString("GenitourinarySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter genitourinary system.
        /// </summary>
        public static string GenitourinarySystemInfoSpan {
            get {
                return ResourceManager.GetString("GenitourinarySystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestational age (weeks).
        /// </summary>
        public static string GestationalAge {
            get {
                return ResourceManager.GetString("GestationalAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gestational age.
        /// </summary>
        public static string GestationalAgeInfoSpan {
            get {
                return ResourceManager.GetString("GestationalAgeInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravida.
        /// </summary>
        public static string Gravida {
            get {
                return ResourceManager.GetString("Gravida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gravida.
        /// </summary>
        public static string GravidaInfoSpan {
            get {
                return ResourceManager.GetString("GravidaInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haematological System.
        /// </summary>
        public static string HaematologicalSystem {
            get {
                return ResourceManager.GetString("HaematologicalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter haematological system.
        /// </summary>
        public static string HaematologicalSystemInfoSpan {
            get {
                return ResourceManager.GetString("HaematologicalSystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head circumference (cm).
        /// </summary>
        public static string HeadCircumference {
            get {
                return ResourceManager.GetString("HeadCircumference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter head circumference.
        /// </summary>
        public static string HeadCircumferenceInfoSpan {
            get {
                return ResourceManager.GetString("HeadCircumferenceInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR (b/min).
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter HR.
        /// </summary>
        public static string HRInfoSpan {
            get {
                return ResourceManager.GetString("HRInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour &amp; Delivery.
        /// </summary>
        public static string LabourAndDelivery {
            get {
                return ResourceManager.GetString("LabourAndDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter labour &amp; delivery.
        /// </summary>
        public static string LabourAndDeliveryInfoSpan {
            get {
                return ResourceManager.GetString("LabourAndDeliveryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour &amp; delivery remarks.
        /// </summary>
        public static string LabourAndDeliveryRemarks {
            get {
                return ResourceManager.GetString("LabourAndDeliveryRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter labour &amp; delivery remarks.
        /// </summary>
        public static string LabourAndDeliveryRemarksInfoSpan {
            get {
                return ResourceManager.GetString("LabourAndDeliveryRemarksInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (cm).
        /// </summary>
        public static string Lenghth {
            get {
                return ResourceManager.GetString("Lenghth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter length.
        /// </summary>
        public static string LenghthInfoSpan {
            get {
                return ResourceManager.GetString("LenghthInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major events in the last 24 hours.
        /// </summary>
        public static string MajorEventsInTheLast24Hours {
            get {
                return ResourceManager.GetString("MajorEventsInTheLast24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter major events in the last 24 hours.
        /// </summary>
        public static string MajorEventsInTheLast24HoursInfoSpan {
            get {
                return ResourceManager.GetString("MajorEventsInTheLast24HoursInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother age.
        /// </summary>
        public static string MotherAge {
            get {
                return ResourceManager.GetString("MotherAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mother age.
        /// </summary>
        public static string MotherAgeInfoSpan {
            get {
                return ResourceManager.GetString("MotherAgeInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow-Ups.
        /// </summary>
        public static string NICUConsultationFollowUpForms {
            get {
                return ResourceManager.GetString("NICUConsultationFollowUpForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online NICU consultation follow-up form.
        /// </summary>
        public static string OnlineNICUConsultationFollowUpForm {
            get {
                return ResourceManager.GetString("OnlineNICUConsultationFollowUpForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online NICU consultation form.
        /// </summary>
        public static string OnlineNICUConsultationForm {
            get {
                return ResourceManager.GetString("OnlineNICUConsultationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter others.
        /// </summary>
        public static string OthersInfoSpan {
            get {
                return ResourceManager.GetString("OthersInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter parity.
        /// </summary>
        public static string ParityInfoSpan {
            get {
                return ResourceManager.GetString("ParityInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Examination.
        /// </summary>
        public static string PhysicalExamination {
            get {
                return ResourceManager.GetString("PhysicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan of care (IVF, Antibiotics, Medications, Labs, investigations, consultations, etc…).
        /// </summary>
        public static string PlanOfCare {
            get {
                return ResourceManager.GetString("PlanOfCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter plan of care.
        /// </summary>
        public static string PlanOfCareInfoSpan {
            get {
                return ResourceManager.GetString("PlanOfCareInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posture.
        /// </summary>
        public static string Posture {
            get {
                return ResourceManager.GetString("Posture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter posture.
        /// </summary>
        public static string PostureInfoSpan {
            get {
                return ResourceManager.GetString("PostureInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnancy and delivery history.
        /// </summary>
        public static string PregnancyAndDeliveryHistory {
            get {
                return ResourceManager.GetString("PregnancyAndDeliveryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Diagnosis &amp; Differential Diagnosis.
        /// </summary>
        public static string PrimaryDiagnosisOrDifferentialDiagnosis {
            get {
                return ResourceManager.GetString("PrimaryDiagnosisOrDifferentialDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter primary diagnosis &amp; differential diagnosis.
        /// </summary>
        public static string PrimaryDiagnosisOrDifferentialDiagnosisInfoSpan {
            get {
                return ResourceManager.GetString("PrimaryDiagnosisOrDifferentialDiagnosisInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem list.
        /// </summary>
        public static string ProblemList {
            get {
                return ResourceManager.GetString("ProblemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter problem list.
        /// </summary>
        public static string ProblemListInfoSpan {
            get {
                return ResourceManager.GetString("ProblemListInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures (Intubation, umbilical line catheterization, chest tube, etc…).
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter procedures.
        /// </summary>
        public static string ProceduresInfoSpan {
            get {
                return ResourceManager.GetString("ProceduresInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychosocial history (Home environment, occupation of father and mother, problems, family support system, etc…).
        /// </summary>
        public static string PsychosocialHistory {
            get {
                return ResourceManager.GetString("PsychosocialHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter psychosocial history.
        /// </summary>
        public static string PsychosocialHistoryInfoSpan {
            get {
                return ResourceManager.GetString("PsychosocialHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBS (mg/dL).
        /// </summary>
        public static string RBS {
            get {
                return ResourceManager.GetString("RBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RBS.
        /// </summary>
        public static string RBSInfoSpan {
            get {
                return ResourceManager.GetString("RBSInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason of admission.
        /// </summary>
        public static string ReasonOfAdmission {
            get {
                return ResourceManager.GetString("ReasonOfAdmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter reason of admission.
        /// </summary>
        public static string ReasonOfAdmissionInfoSpan {
            get {
                return ResourceManager.GetString("ReasonOfAdmissionInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter remarks.
        /// </summary>
        public static string RemarksInfoSpan {
            get {
                return ResourceManager.GetString("RemarksInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory System.
        /// </summary>
        public static string RespiratorySystem {
            get {
                return ResourceManager.GetString("RespiratorySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter respiratory system.
        /// </summary>
        public static string RespiratorySystemInfoSpan {
            get {
                return ResourceManager.GetString("RespiratorySystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuscitation.
        /// </summary>
        public static string Resuscitation {
            get {
                return ResourceManager.GetString("Resuscitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter resuscitation.
        /// </summary>
        public static string ResuscitationInfoSpan {
            get {
                return ResourceManager.GetString("ResuscitationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuscitation remarks.
        /// </summary>
        public static string ResuscitationRemarks {
            get {
                return ResourceManager.GetString("ResuscitationRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter resuscitation remarks.
        /// </summary>
        public static string ResuscitationRemarksInfoSpan {
            get {
                return ResourceManager.GetString("ResuscitationRemarksInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR (b/min).
        /// </summary>
        public static string RR {
            get {
                return ResourceManager.GetString("RR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RR.
        /// </summary>
        public static string RRInfoSpan {
            get {
                return ResourceManager.GetString("RRInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show loaded successfully.
        /// </summary>
        public static string ShowLoadedSuccessfully {
            get {
                return ResourceManager.GetString("ShowLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string Skin {
            get {
                return ResourceManager.GetString("Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter skin.
        /// </summary>
        public static string SkinInfoSpan {
            get {
                return ResourceManager.GetString("SkinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpO2 %.
        /// </summary>
        public static string SpO2 {
            get {
                return ResourceManager.GetString("SpO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter SpO2 %.
        /// </summary>
        public static string SpO2InfoSpan {
            get {
                return ResourceManager.GetString("SpO2InfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp (C).
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter temp.
        /// </summary>
        public static string TempInfoSpan {
            get {
                return ResourceManager.GetString("TempInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vital Signs.
        /// </summary>
        public static string VitalSigns {
            get {
                return ResourceManager.GetString("VitalSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (gram).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter weight.
        /// </summary>
        public static string WeightInfoSpan {
            get {
                return ResourceManager.GetString("WeightInfoSpan", resourceCulture);
            }
        }
    }
}
