//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NPICUResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NPICUResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.NPICUResource", typeof(NPICUResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add N/PICU Case.
        /// </summary>
        public static string AddNPICUCase {
            get {
                return ResourceManager.GetString("AddNPICUCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Type.
        /// </summary>
        public static string CaseType {
            get {
                return ResourceManager.GetString("CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation follow-up form.
        /// </summary>
        public static string ConsultationFollowUpForm {
            get {
                return ResourceManager.GetString("ConsultationFollowUpForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Form.
        /// </summary>
        public static string ConsultationForm {
            get {
                return ResourceManager.GetString("ConsultationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Section.
        /// </summary>
        public static string NPICUConsultantSection {
            get {
                return ResourceManager.GetString("NPICUConsultantSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigations.
        /// </summary>
        public static string NPICUInvestigation {
            get {
                return ResourceManager.GetString("NPICUInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Full Name.
        /// </summary>
        public static string PatientFullName {
            get {
                return ResourceManager.GetString("PatientFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update N/PICU Case.
        /// </summary>
        public static string UpdateNPICUCase {
            get {
                return ResourceManager.GetString("UpdateNPICUCase", resourceCulture);
            }
        }
    }
}
