//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NPICUInvestigationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NPICUInvestigationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.NPICUInvestigationResource", typeof(NPICUInvestigationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Investigation.
        /// </summary>
        public static string AddInvestigation {
            get {
                return ResourceManager.GetString("AddInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        public static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter AG.
        /// </summary>
        public static string AGInfoSpan {
            get {
                return ResourceManager.GetString("AGInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albumin (g/dL).
        /// </summary>
        public static string Albumin {
            get {
                return ResourceManager.GetString("Albumin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Albumin.
        /// </summary>
        public static string AlbuminInfoSpan {
            get {
                return ResourceManager.GetString("AlbuminInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkaline Phosphatase.
        /// </summary>
        public static string AlkalinePhosphatase {
            get {
                return ResourceManager.GetString("AlkalinePhosphatase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Alkaline Phosphatase.
        /// </summary>
        public static string AlkalinePhosphataseInfoSpan {
            get {
                return ResourceManager.GetString("AlkalinePhosphataseInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT.
        /// </summary>
        public static string ALT {
            get {
                return ResourceManager.GetString("ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter ALT.
        /// </summary>
        public static string ALTInfoSpan {
            get {
                return ResourceManager.GetString("ALTInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammonia (µmol/L).
        /// </summary>
        public static string Ammonia {
            get {
                return ResourceManager.GetString("Ammonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Ammonia.
        /// </summary>
        public static string AmmoniaInfoSpan {
            get {
                return ResourceManager.GetString("AmmoniaInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AST.
        /// </summary>
        public static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter AST.
        /// </summary>
        public static string ASTInfoSpan {
            get {
                return ResourceManager.GetString("ASTInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basophils %.
        /// </summary>
        public static string Basophils {
            get {
                return ResourceManager.GetString("Basophils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Basophils.
        /// </summary>
        public static string BasophilsInfoSpan {
            get {
                return ResourceManager.GetString("BasophilsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter BE.
        /// </summary>
        public static string BEInfoSpan {
            get {
                return ResourceManager.GetString("BEInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biochemistry.
        /// </summary>
        public static string Biochemistry {
            get {
                return ResourceManager.GetString("Biochemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Culture.
        /// </summary>
        public static string BloodCulture {
            get {
                return ResourceManager.GetString("BloodCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Blood Culture.
        /// </summary>
        public static string BloodCultureInfoSpan {
            get {
                return ResourceManager.GetString("BloodCultureInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Gases.
        /// </summary>
        public static string BloodGases {
            get {
                return ResourceManager.GetString("BloodGases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter blood gases.
        /// </summary>
        public static string BloodGasesInfoSpan {
            get {
                return ResourceManager.GetString("BloodGasesInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium (mg/dL).
        /// </summary>
        public static string Calcium {
            get {
                return ResourceManager.GetString("Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Calcium.
        /// </summary>
        public static string CalciumInfoSpan {
            get {
                return ResourceManager.GetString("CalciumInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBC With Differential.
        /// </summary>
        public static string CBCWithDifferential {
            get {
                return ResourceManager.GetString("CBCWithDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest &amp; Abdomen X-ray.
        /// </summary>
        public static string ChestAndAbdomenXray {
            get {
                return ResourceManager.GetString("ChestAndAbdomenXray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Chest &amp; Abdomen X-ray.
        /// </summary>
        public static string ChestAndAbdomenXrayInfoSpan {
            get {
                return ResourceManager.GetString("ChestAndAbdomenXrayInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chloride.
        /// </summary>
        public static string Chloride {
            get {
                return ResourceManager.GetString("Chloride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Chloride.
        /// </summary>
        public static string ChlorideInfoSpan {
            get {
                return ResourceManager.GetString("ChlorideInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine.
        /// </summary>
        public static string Creatinine {
            get {
                return ResourceManager.GetString("Creatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Creatinine.
        /// </summary>
        public static string CreatinineInfoSpan {
            get {
                return ResourceManager.GetString("CreatinineInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRP.
        /// </summary>
        public static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CRP.
        /// </summary>
        public static string CRPInfoSpan {
            get {
                return ResourceManager.GetString("CRPInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSF culture.
        /// </summary>
        public static string CSFCulture {
            get {
                return ResourceManager.GetString("CSFCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CSF culture.
        /// </summary>
        public static string CSFCultureInfoSpan {
            get {
                return ResourceManager.GetString("CSFCultureInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSF glucose.
        /// </summary>
        public static string CSFGlucose {
            get {
                return ResourceManager.GetString("CSFGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CSF glucose.
        /// </summary>
        public static string CSFGlucoseInfoSpan {
            get {
                return ResourceManager.GetString("CSFGlucoseInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSF gram stain.
        /// </summary>
        public static string CSFGramStain {
            get {
                return ResourceManager.GetString("CSFGramStain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CSF gram stain.
        /// </summary>
        public static string CSFGramStainInfoSpan {
            get {
                return ResourceManager.GetString("CSFGramStainInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSF Latex agglutination.
        /// </summary>
        public static string CSFLatexAgglutination {
            get {
                return ResourceManager.GetString("CSFLatexAgglutination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CSF Latex agglutination.
        /// </summary>
        public static string CSFLatexAgglutinationInfoSpan {
            get {
                return ResourceManager.GetString("CSFLatexAgglutinationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSF protein.
        /// </summary>
        public static string CSFProtein {
            get {
                return ResourceManager.GetString("CSFProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CSF protein.
        /// </summary>
        public static string CSFProteinInfoSpan {
            get {
                return ResourceManager.GetString("CSFProteinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSF Study.
        /// </summary>
        public static string CSFStudy {
            get {
                return ResourceManager.GetString("CSFStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct bilirubin(mg/dL).
        /// </summary>
        public static string DirectBilirubin {
            get {
                return ResourceManager.GetString("DirectBilirubin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Direct bilirubin.
        /// </summary>
        public static string DirectBilirubinInfoSpan {
            get {
                return ResourceManager.GetString("DirectBilirubinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echocardiography.
        /// </summary>
        public static string Echocardiography {
            get {
                return ResourceManager.GetString("Echocardiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Echocardiography.
        /// </summary>
        public static string EchocardiographyInfoSpan {
            get {
                return ResourceManager.GetString("EchocardiographyInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrolytes.
        /// </summary>
        public static string Electrolytes {
            get {
                return ResourceManager.GetString("Electrolytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eosinophils %.
        /// </summary>
        public static string Eosinophils {
            get {
                return ResourceManager.GetString("Eosinophils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Eosinophils.
        /// </summary>
        public static string EosinophilsInfoSpan {
            get {
                return ResourceManager.GetString("EosinophilsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCO3.
        /// </summary>
        public static string HCO3 {
            get {
                return ResourceManager.GetString("HCO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter HCO3.
        /// </summary>
        public static string HCO3InfoSpan {
            get {
                return ResourceManager.GetString("HCO3InfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hematocrit %.
        /// </summary>
        public static string Hematocrit {
            get {
                return ResourceManager.GetString("Hematocrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Hematocrit.
        /// </summary>
        public static string HematocritInfoSpan {
            get {
                return ResourceManager.GetString("HematocritInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemoglobin (g/dL).
        /// </summary>
        public static string Hemoglobin {
            get {
                return ResourceManager.GetString("Hemoglobin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Hemoglobin.
        /// </summary>
        public static string HemoglobinInfoSpan {
            get {
                return ResourceManager.GetString("HemoglobinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigations.
        /// </summary>
        public static string Investigations {
            get {
                return ResourceManager.GetString("Investigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactate (mmol/L).
        /// </summary>
        public static string Lactate {
            get {
                return ResourceManager.GetString("Lactate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Lactate.
        /// </summary>
        public static string LactateInfoSpan {
            get {
                return ResourceManager.GetString("LactateInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymphocytes %.
        /// </summary>
        public static string Lymphocytes {
            get {
                return ResourceManager.GetString("Lymphocytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Lymphocytes.
        /// </summary>
        public static string LymphocytesInfoSpan {
            get {
                return ResourceManager.GetString("LymphocytesInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium.
        /// </summary>
        public static string Magnesium {
            get {
                return ResourceManager.GetString("Magnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Magnesium.
        /// </summary>
        public static string MagnesiumInfoSpan {
            get {
                return ResourceManager.GetString("MagnesiumInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCV.
        /// </summary>
        public static string MCV {
            get {
                return ResourceManager.GetString("MCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter MCV.
        /// </summary>
        public static string MCVInfoSpan {
            get {
                return ResourceManager.GetString("MCVInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutrophils %.
        /// </summary>
        public static string Neutrophils {
            get {
                return ResourceManager.GetString("Neutrophils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Neutrophils.
        /// </summary>
        public static string NeutrophilsInfoSpan {
            get {
                return ResourceManager.GetString("NeutrophilsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Others.
        /// </summary>
        public static string OthersInfoSpan {
            get {
                return ResourceManager.GetString("OthersInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCO2.
        /// </summary>
        public static string PCO2 {
            get {
                return ResourceManager.GetString("PCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter PCO2.
        /// </summary>
        public static string PCO2InfoSpan {
            get {
                return ResourceManager.GetString("PCO2InfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        public static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter PH.
        /// </summary>
        public static string PHInfoSpan {
            get {
                return ResourceManager.GetString("PHInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorous.
        /// </summary>
        public static string Phosphorous {
            get {
                return ResourceManager.GetString("Phosphorous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Phosphorous.
        /// </summary>
        public static string PhosphorousInfoSpan {
            get {
                return ResourceManager.GetString("PhosphorousInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platelets.
        /// </summary>
        public static string Platelets {
            get {
                return ResourceManager.GetString("Platelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Platelets.
        /// </summary>
        public static string PlateletsInfoSpan {
            get {
                return ResourceManager.GetString("PlateletsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO2.
        /// </summary>
        public static string PO2 {
            get {
                return ResourceManager.GetString("PO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter PO2.
        /// </summary>
        public static string PO2InfoSpan {
            get {
                return ResourceManager.GetString("PO2InfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        public static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Potassium.
        /// </summary>
        public static string PotassiumInfoSpan {
            get {
                return ResourceManager.GetString("PotassiumInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBCs.
        /// </summary>
        public static string RBCs {
            get {
                return ResourceManager.GetString("RBCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RBCs.
        /// </summary>
        public static string RBCsInfoSpan {
            get {
                return ResourceManager.GetString("RBCsInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBS at lumbar puncture.
        /// </summary>
        public static string RBSAtLumbarPuncture {
            get {
                return ResourceManager.GetString("RBSAtLumbarPuncture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RBS at lumbar puncture.
        /// </summary>
        public static string RBSAtLumbarPunctureInfoSpan {
            get {
                return ResourceManager.GetString("RBSAtLumbarPunctureInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDW %.
        /// </summary>
        public static string RDW {
            get {
                return ResourceManager.GetString("RDW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RDW.
        /// </summary>
        public static string RDWInfoSpan {
            get {
                return ResourceManager.GetString("RDWInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reticulocytes %.
        /// </summary>
        public static string Reticulocytes {
            get {
                return ResourceManager.GetString("Reticulocytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Reticulocytes.
        /// </summary>
        public static string ReticulocytesInfoSpan {
            get {
                return ResourceManager.GetString("ReticulocytesInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serum glucose (mg/dL).
        /// </summary>
        public static string SerumGlucose {
            get {
                return ResourceManager.GetString("SerumGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Serum glucose.
        /// </summary>
        public static string SerumGlucoseInfoSpan {
            get {
                return ResourceManager.GetString("SerumGlucoseInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Sodium.
        /// </summary>
        public static string SodiumInfoSpan {
            get {
                return ResourceManager.GetString("SodiumInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total bilirubin (mg/dL).
        /// </summary>
        public static string TotalBilirubin {
            get {
                return ResourceManager.GetString("TotalBilirubin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Total Bilirubin.
        /// </summary>
        public static string TotalBilirubinInfoSpan {
            get {
                return ResourceManager.GetString("TotalBilirubinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Protein (g/dL).
        /// </summary>
        public static string TotalProtein {
            get {
                return ResourceManager.GetString("TotalProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Total Protein.
        /// </summary>
        public static string TotalProteinInfoSpan {
            get {
                return ResourceManager.GetString("TotalProteinInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urea.
        /// </summary>
        public static string Urea {
            get {
                return ResourceManager.GetString("Urea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Urea.
        /// </summary>
        public static string UreaInfoSpan {
            get {
                return ResourceManager.GetString("UreaInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine analysis and culture.
        /// </summary>
        public static string UrineAnalysisAndCulture {
            get {
                return ResourceManager.GetString("UrineAnalysisAndCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Urine analysis and culture.
        /// </summary>
        public static string UrineAnalysisAndCultureInfoSpan {
            get {
                return ResourceManager.GetString("UrineAnalysisAndCultureInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBCs.
        /// </summary>
        public static string WBCs {
            get {
                return ResourceManager.GetString("WBCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter WBCs.
        /// </summary>
        public static string WBCsInfoSpan {
            get {
                return ResourceManager.GetString("WBCsInfoSpan", resourceCulture);
            }
        }
    }
}
