//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatientResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.PatientResource", typeof(PatientResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mental Health Case.
        /// </summary>
        public static string AddMentalHealthCase {
            get {
                return ResourceManager.GetString("AddMentalHealthCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add NPICU Case.
        /// </summary>
        public static string AddNPICUCase {
            get {
                return ResourceManager.GetString("AddNPICUCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address.
        /// </summary>
        public static string AddressInfoSpan {
            get {
                return ResourceManager.GetString("AddressInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ICU Case.
        /// </summary>
        public static string AddTeleICUCase {
            get {
                return ResourceManager.GetString("AddTeleICUCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter birth date.
        /// </summary>
        public static string BirthDateInfoSpan {
            get {
                return ResourceManager.GetString("BirthDateInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood group.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter blood group.
        /// </summary>
        public static string BloodTypeInfoSpan {
            get {
                return ResourceManager.GetString("BloodTypeInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter department.
        /// </summary>
        public static string DepartmentInfoSpan {
            get {
                return ResourceManager.GetString("DepartmentInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open new case for this patient, ther is already an open case !!.
        /// </summary>
        public static string ErrorAddCase {
            get {
                return ResourceManager.GetString("ErrorAddCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter father name.
        /// </summary>
        public static string FatherNameInfoSpan {
            get {
                return ResourceManager.GetString("FatherNameInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name.
        /// </summary>
        public static string FirstNameInfoSpan {
            get {
                return ResourceManager.GetString("FirstNameInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gender.
        /// </summary>
        public static string GenderInfoSpan {
            get {
                return ResourceManager.GetString("GenderInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name.
        /// </summary>
        public static string LastNameInfoSpan {
            get {
                return ResourceManager.GetString("LastNameInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter marital status.
        /// </summary>
        public static string MaritalStatusInfoSpan {
            get {
                return ResourceManager.GetString("MaritalStatusInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mother name.
        /// </summary>
        public static string MotherNameInfoSpan {
            get {
                return ResourceManager.GetString("MotherNameInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient.
        /// </summary>
        public static string NewPatient {
            get {
                return ResourceManager.GetString("NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Code.
        /// </summary>
        public static string PatientCode {
            get {
                return ResourceManager.GetString("PatientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone number.
        /// </summary>
        public static string PhoneNumberInfoSpan {
            get {
                return ResourceManager.GetString("PhoneNumberInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter place of birth.
        /// </summary>
        public static string PlaceOfBirthInfoSpan {
            get {
                return ResourceManager.GetString("PlaceOfBirthInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Patient.
        /// </summary>
        public static string UpdatePatient {
            get {
                return ResourceManager.GetString("UpdatePatient", resourceCulture);
            }
        }
    }
}
