//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PICUConsultationFormFollowUPResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PICUConsultationFormFollowUPResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.PICUConsultationFormFollowUPResource" +
                            "", typeof(PICUConsultationFormFollowUPResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Follow-Up.
        /// </summary>
        public static string AddFollowUp {
            get {
                return ResourceManager.GetString("AddFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter allergy.
        /// </summary>
        public static string AllergyInfoSpan {
            get {
                return ResourceManager.GetString("AllergyInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP.
        /// </summary>
        public static string BP {
            get {
                return ResourceManager.GetString("BP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter BP.
        /// </summary>
        public static string BPInfoSpan {
            get {
                return ResourceManager.GetString("BPInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiovascular System.
        /// </summary>
        public static string CardiovascularSystem {
            get {
                return ResourceManager.GetString("CardiovascularSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter cardiovascular system.
        /// </summary>
        public static string CardiovascularSystemInfoSpan {
            get {
                return ResourceManager.GetString("CardiovascularSystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Nervous System.
        /// </summary>
        public static string CentralNervousSystem {
            get {
                return ResourceManager.GetString("CentralNervousSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter central nervous system.
        /// </summary>
        public static string CentralNervousSystemInfoSpan {
            get {
                return ResourceManager.GetString("CentralNervousSystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with family (Reason for admission, medical or surgical management, education, family support, etc…).
        /// </summary>
        public static string CommunicationWithFamily {
            get {
                return ResourceManager.GetString("CommunicationWithFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter communication with family.
        /// </summary>
        public static string CommunicationWithFamilyInfoSpan {
            get {
                return ResourceManager.GetString("CommunicationWithFamilyInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Medical &amp; Psychosocial History.
        /// </summary>
        public static string FamilyMedicalAndPsychosocialHistory {
            get {
                return ResourceManager.GetString("FamilyMedicalAndPsychosocialHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter family medical &amp; psychosocial history.
        /// </summary>
        public static string FamilyMedicalAndPsychosocialHistoryInfoSpan {
            get {
                return ResourceManager.GetString("FamilyMedicalAndPsychosocialHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrointestinal Tract.
        /// </summary>
        public static string GastrointestinalTract {
            get {
                return ResourceManager.GetString("GastrointestinalTract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrointestinal Tract &amp; Genitourinary System.
        /// </summary>
        public static string GastrointestinalTractAndGenitourinarySystem {
            get {
                return ResourceManager.GetString("GastrointestinalTractAndGenitourinarySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gastrointestinal tract &amp; genitourinary system.
        /// </summary>
        public static string GastrointestinalTractAndGenitourinarySystemInfoSpan {
            get {
                return ResourceManager.GetString("GastrointestinalTractAndGenitourinarySystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gastrointestinal tract.
        /// </summary>
        public static string GastrointestinalTractInfoSpan {
            get {
                return ResourceManager.GetString("GastrointestinalTractInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Appearance.
        /// </summary>
        public static string GeneralAppearance {
            get {
                return ResourceManager.GetString("GeneralAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genitourinary System.
        /// </summary>
        public static string GenitourinarySystem {
            get {
                return ResourceManager.GetString("GenitourinarySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter genitourinary system.
        /// </summary>
        public static string GenitourinarySystemInfoSpan {
            get {
                return ResourceManager.GetString("GenitourinarySystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haematological System.
        /// </summary>
        public static string HaematologicalSystem {
            get {
                return ResourceManager.GetString("HaematologicalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter haematological system.
        /// </summary>
        public static string HaematologicalSystemInfoSpan {
            get {
                return ResourceManager.GetString("HaematologicalSystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head circumference (cm).
        /// </summary>
        public static string HeadCircumference {
            get {
                return ResourceManager.GetString("HeadCircumference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter head circumference.
        /// </summary>
        public static string HeadCircumferenceInfoSpan {
            get {
                return ResourceManager.GetString("HeadCircumferenceInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of present illness.
        /// </summary>
        public static string HistoryOfPresentIllness {
            get {
                return ResourceManager.GetString("HistoryOfPresentIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter history of present illness.
        /// </summary>
        public static string HistoryOfPresentIllnessInfoSpan {
            get {
                return ResourceManager.GetString("HistoryOfPresentIllnessInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR (b/min).
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter HR.
        /// </summary>
        public static string HRInfoSpan {
            get {
                return ResourceManager.GetString("HRInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunization.
        /// </summary>
        public static string Immunization {
            get {
                return ResourceManager.GetString("Immunization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter immunization.
        /// </summary>
        public static string ImmunizationInfoSpan {
            get {
                return ResourceManager.GetString("ImmunizationInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (cm).
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter length.
        /// </summary>
        public static string LengthInfoSpan {
            get {
                return ResourceManager.GetString("LengthInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Complaint.
        /// </summary>
        public static string MainComplaint {
            get {
                return ResourceManager.GetString("MainComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter main complaint.
        /// </summary>
        public static string MainComplaintInfoSpan {
            get {
                return ResourceManager.GetString("MainComplaintInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major events in the last 24 hours.
        /// </summary>
        public static string MajorEventsInTheLast24Hours {
            get {
                return ResourceManager.GetString("MajorEventsInTheLast24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter major events in the last 24 hours.
        /// </summary>
        public static string MajorEventsInTheLast24HoursInfoSpan {
            get {
                return ResourceManager.GetString("MajorEventsInTheLast24HoursInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical &amp; Surgical History.
        /// </summary>
        public static string MedicalAndSurgicalHistory {
            get {
                return ResourceManager.GetString("MedicalAndSurgicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter medical &amp; surgical history.
        /// </summary>
        public static string MedicalAndSurgicalHistoryInfoSpan {
            get {
                return ResourceManager.GetString("MedicalAndSurgicalHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritional History.
        /// </summary>
        public static string NutritionalHistory {
            get {
                return ResourceManager.GetString("NutritionalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter nutritional history.
        /// </summary>
        public static string NutritionalHistoryInfoSpan {
            get {
                return ResourceManager.GetString("NutritionalHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online PICU Consultation Follow-up Form.
        /// </summary>
        public static string OnlinePICUConsultationFollowUpForm {
            get {
                return ResourceManager.GetString("OnlinePICUConsultationFollowUpForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online PICU Consultation Form.
        /// </summary>
        public static string OnlinePICUConsultationForm {
            get {
                return ResourceManager.GetString("OnlinePICUConsultationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter others.
        /// </summary>
        public static string OthersInfoSpan {
            get {
                return ResourceManager.GetString("OthersInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Medical History.
        /// </summary>
        public static string PastMedicalHistory {
            get {
                return ResourceManager.GetString("PastMedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Examination.
        /// </summary>
        public static string PhysicalExamination {
            get {
                return ResourceManager.GetString("PhysicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online PICU Consultation Follow-up Form.
        /// </summary>
        public static string PICUConsultationFollowUpForms {
            get {
                return ResourceManager.GetString("PICUConsultationFollowUpForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan of care (IVF, antibiotics, medications, labs, investigations, consultations, etc…).
        /// </summary>
        public static string PlanOfCare {
            get {
                return ResourceManager.GetString("PlanOfCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter plan of care.
        /// </summary>
        public static string PlanOfCareInfoSpan {
            get {
                return ResourceManager.GetString("PlanOfCareInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnancy and Delivery History.
        /// </summary>
        public static string PregnancyAndDeliveryHistory {
            get {
                return ResourceManager.GetString("PregnancyAndDeliveryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pregnancy and delivery history.
        /// </summary>
        public static string PregnancyAndDeliveryHistoryInfoSpan {
            get {
                return ResourceManager.GetString("PregnancyAndDeliveryHistoryInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Diagnosis &amp; Differential Diagnosis.
        /// </summary>
        public static string PrimaryDiagnosisOrDifferentialDiagnosis {
            get {
                return ResourceManager.GetString("PrimaryDiagnosisOrDifferentialDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter primary diagnosis &amp; differential diagnosis.
        /// </summary>
        public static string PrimaryDiagnosisOrDifferentialDiagnosisInfoSpan {
            get {
                return ResourceManager.GetString("PrimaryDiagnosisOrDifferentialDiagnosisInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem List.
        /// </summary>
        public static string ProblemList {
            get {
                return ResourceManager.GetString("ProblemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter problem list.
        /// </summary>
        public static string ProblemListInfoSpan {
            get {
                return ResourceManager.GetString("ProblemListInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures (Intubation, umbilical line catheterization, chest tube, etc…).
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter procedures.
        /// </summary>
        public static string ProceduresInfoSpan {
            get {
                return ResourceManager.GetString("ProceduresInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychomotor Development.
        /// </summary>
        public static string PsychomotorDevelopment {
            get {
                return ResourceManager.GetString("PsychomotorDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter psychomotor development.
        /// </summary>
        public static string PsychomotorDevelopmentInfoSpan {
            get {
                return ResourceManager.GetString("PsychomotorDevelopmentInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBS (mg/dL).
        /// </summary>
        public static string RBS {
            get {
                return ResourceManager.GetString("RBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RBS.
        /// </summary>
        public static string RBSInfoSpan {
            get {
                return ResourceManager.GetString("RBSInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory System.
        /// </summary>
        public static string Respiratory_System {
            get {
                return ResourceManager.GetString("Respiratory System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory System.
        /// </summary>
        public static string RespiratorySystem {
            get {
                return ResourceManager.GetString("RespiratorySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter respiratory system.
        /// </summary>
        public static string RespiratorySystemInfoSpan {
            get {
                return ResourceManager.GetString("RespiratorySystemInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR (b/min).
        /// </summary>
        public static string RR {
            get {
                return ResourceManager.GetString("RR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RR.
        /// </summary>
        public static string RRInfoSpan {
            get {
                return ResourceManager.GetString("RRInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Successfully.
        /// </summary>
        public static string ShowLoadedSuccessfully {
            get {
                return ResourceManager.GetString("ShowLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpO2 %.
        /// </summary>
        public static string SpO2 {
            get {
                return ResourceManager.GetString("SpO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter SpO2.
        /// </summary>
        public static string SpO2InfoSpan {
            get {
                return ResourceManager.GetString("SpO2InfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp (C).
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Temp.
        /// </summary>
        public static string TempInfoSpan {
            get {
                return ResourceManager.GetString("TempInfoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vital Signs.
        /// </summary>
        public static string VitalSigns {
            get {
                return ResourceManager.GetString("VitalSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (gram).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter weight.
        /// </summary>
        public static string WeightInfoSpan {
            get {
                return ResourceManager.GetString("WeightInfoSpan", resourceCulture);
            }
        }
    }
}
