//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulevardManagement.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeleICUResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeleICUResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulevardManagement.WebApplication.Resources.TeleICUResource", typeof(TeleICUResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Story.
        /// </summary>
        public static string ClinicalStory {
            get {
                return ResourceManager.GetString("ClinicalStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Section.
        /// </summary>
        public static string ConsultationForm {
            get {
                return ResourceManager.GetString("ConsultationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Consultation Form.
        /// </summary>
        public static string InternalConsultationForm {
            get {
                return ResourceManager.GetString("InternalConsultationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Unit.
        /// </summary>
        public static string LabUnit {
            get {
                return ResourceManager.GetString("LabUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Daily Schedule Table.
        /// </summary>
        public static string MedicationDailyScheduleTable {
            get {
                return ResourceManager.GetString("MedicationDailyScheduleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Exit Status Report.
        /// </summary>
        public static string PatientExitStatusReport {
            get {
                return ResourceManager.GetString("PatientExitStatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Full Name.
        /// </summary>
        public static string PatientFullName {
            get {
                return ResourceManager.GetString("PatientFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string StickyNote {
            get {
                return ResourceManager.GetString("StickyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ICU Case.
        /// </summary>
        public static string UpdateICUCase {
            get {
                return ResourceManager.GetString("UpdateICUCase", resourceCulture);
            }
        }
    }
}
