//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleA.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnnotationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnnotationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripleA.Utilities.Resources.AnnotationMessages", typeof(AnnotationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only letters (a-z) allowed.
        /// </summary>
        public static string Alphabets {
            get {
                return ResourceManager.GetString("Alphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only letters (a-z) and ({0}) are allowed.
        /// </summary>
        public static string AlphabetsAnd {
            get {
                return ResourceManager.GetString("AlphabetsAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only letters (a-z) and numbers (0-9) are allowed.
        /// </summary>
        public static string Alphanumeric {
            get {
                return ResourceManager.GetString("Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only letters (a-z), numbers (0-9) and ({0}) are allowed.
        /// </summary>
        public static string AlphanumericAnd {
            get {
                return ResourceManager.GetString("AlphanumericAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only letters (a-z), numbers (0-9) and ({0}) are allowed and should start with letter.
        /// </summary>
        public static string AlphanumericAndTrim {
            get {
                return ResourceManager.GetString("AlphanumericAndTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only letters (a-z) and numbers (0-9) are allowed and should start with letter.
        /// </summary>
        public static string AlphanumericTrim {
            get {
                return ResourceManager.GetString("AlphanumericTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string ComparePasswords {
            get {
                return ResourceManager.GetString("ComparePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number can only contain numbers, space, and the characters: ( - ), ( # ), and ( + ).
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date.
        /// </summary>
        public static string DataType_Date {
            get {
                return ResourceManager.GetString("DataType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid decimal number.
        /// </summary>
        public static string DecimalNumber {
            get {
                return ResourceManager.GetString("DecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter non-Default Value.
        /// </summary>
        public static string DisallowEnumValue {
            get {
                return ResourceManager.GetString("DisallowEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least select {0} {1}.
        /// </summary>
        public static string MinimumElements {
            get {
                return ResourceManager.GetString("MinimumElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to agree to the terms and conditions.
        /// </summary>
        public static string MustBeTrue {
            get {
                return ResourceManager.GetString("MustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filed shall contain combination of numbers and alphabets.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between ({0}) and ({1}).
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters should be {0}.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters cannot exceeded {0}.
        /// </summary>
        public static string StringMaximumLength {
            get {
                return ResourceManager.GetString("StringMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters should be between {0} and {1}.
        /// </summary>
        public static string StringRange {
            get {
                return ResourceManager.GetString("StringRange", resourceCulture);
            }
        }
    }
}
